### ISSUE TITLE
Support for Laravel Mix

### ISSUE THREAD

**Issue by LasseRafn** [sknoslo/laravel-elixir-svgstore#5]
Is Laravel Mix support in the pipeline, or is it something worth working on? I'd gladly help.

**Comment by sknoslo** [comment]
I haven't personally upgraded to Mix yet, but it is my understanding that Mix is just a wrapper for webpack. You should be able to just use something like [this](https://github.com/mrsum/webpack-svgstore-plugin) without much hassle. Hope that helps.

**Comment by LasseRafn** [comment]
Makes sense, thanks! 👍
